### ISSUE TITLE
INSTR_CREATE_mov_st in instrument_edge_coverage

### ISSUE THREAD

**Issue by eltuerto** [ivanfratric/winafl#5] opened 2016-08-11 23:25 UTC
I am learning DynamoRIO along with winafl usage so my debugging skills in the DR environment are still lame, I apologize for not having a solid proof of what I am asking.

In the function `instrument_edge_coverage`

You have the following code but there is no `instrlist_meta_preinsert` call afterwards like in the other instructions, is this how it's supposed to be? Are we not updating the previous_offset at the end?

```
//store the new value
offset = (offset >> 1)&(MAP_SIZE - 1);
opnd1 = OPND_CREATE_ABSMEM(&(winafl_data.previous_offset), OPSZ_4);
opnd2 = OPND_CREATE_INT32(offset);
INSTR_CREATE_mov_st(drcontext, opnd1, opnd2);
```

**Comment by ivanfratric** [comment] 2016-08-12 16:25
Nice catch! This indeed looks like a bug.

Unfortunately I'm travelling for another week or so and don't have my Windows machine with me, so realistically I'm going to release a new version with the fix on the week of August 22.

Without updating the previous_offset, what we are getting out of WinAFL is essentially basic block coverage instead of edge coverage, so it's not a complete disaster but certainly not what the author intended :-)

**Comment by ivanfratric** [comment] 2016-08-26 13:19
The good news is that this is now fixed and edge coverage seems to be working.

The bad news is that edge coverage doesn't behave as well as expected, apparently through no fault of WinAFL. The problem is that if any of the coverage modules executes two or more threads at the same time, every new context switch is going to be (wrongly) interpreted as new coverage. For example, test_gdiplus fuzz in edge coverage mode is quickly going to produce hundreds of new samples, when in reality only few of those are going to contain new coverage. This is unfortunate because on a casual look the app doesn't appear to require multiple threads. On the other hand, a more simple test.exe fuzz is going to run equally well in both bb and edge coverage mode.

As a result of this I decided to use bb mode as the default, in order for the default settings to work well for more applications (this can be changed by setting the -covtype edge instrumentation flag, of course).

**Closed by ivanfratric** 2016-08-26 13:19 UTC
